### ISSUE TITLE
About the backbone pretrained weights from facebookresearch/VMZ

### ISSUE THREAD

**Issue by WilsonAir** [Schmiddo/d2conv3d#2]
I follow the instruction to download the backbone files in _https://github.com/facebookresearch/VMZ/blob/main/c2/tutorials/model_zoo.md_, but the snapshot file of this site is '.pkl' file and your weights path in _config/model/backbone/irCSN152.yaml_ is a '.pth' file, 

then:

```
Traceback (most recent call last):

  File "/media/wilson/SD_Data/DE/video_shadow/d2conv3d-main/main.py", line 51, in main
    model = SaliencyModel(cfg)
  File "/media/wilson/SD_Data/DE/video_shadow/d2conv3d-main/experiments/saliency.py", line 24, in __init__
    self.model = build_network(hparams.model)
  File "/media/wilson/SD_Data/DE/video_shadow/d2conv3d-main/utils/construct.py", line 44, in build_network
    return retrieve("network", cfg.name)(cfg)
  File "/media/wilson/SD_Data/DE/video_shadow/d2conv3d-main/network/segmentation/encoder_decoder.py", line 17, in __init__
    backbone = build_backbone(cfg.backbone)
  File "/media/wilson/SD_Data/DE/video_shadow/d2conv3d-main/utils/construct.py", line 62, in build_backbone
    load_weights(
  File "/media/wilson/SD_Data/DE/video_shadow/d2conv3d-main/utils/util.py", line 144, in load_weights
    state_dict = torch.load(weights_path, map_location="cpu", encoding="utf-8")
  File "/home/wilson/anaconda3/envs/d2conv3d/lib/python3.8/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/wilson/anaconda3/envs/d2conv3d/lib/python3.8/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xde in position 0: invalid continuation byte

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

and I have tried to revise the line 84 in utils/util.py:
```
state_dict = torch.load(weights_path, map_location="cpu")
to
state_dict = torch.load(weights_path, map_location="cpu",, encoding="latin1")

```
something wrong:

```
Traceback (most recent call last):
  File "/media/wilson/SD_Data/DE/video_shadow/d2conv3d-main/main.py", line 51, in main
    model = SaliencyModel(cfg)
  File "/media/wilson/SD_Data/DE/video_shadow/d2conv3d-main/experiments/saliency.py", line 24, in __init__
    self.model = build_network(hparams.model)
  File "/media/wilson/SD_Data/DE/video_shadow/d2conv3d-main/utils/construct.py", line 44, in build_network
    return retrieve("network", cfg.name)(cfg)
  File "/media/wilson/SD_Data/DE/video_shadow/d2conv3d-main/network/segmentation/encoder_decoder.py", line 17, in __init__
    backbone = build_backbone(cfg.backbone)
  File "/media/wilson/SD_Data/DE/video_shadow/d2conv3d-main/utils/construct.py", line 62, in build_backbone
    load_weights(
  File "/media/wilson/SD_Data/DE/video_shadow/d2conv3d-main/utils/util.py", line 144, in load_weights
    state_dict = torch.load(weights_path, map_location="cpu", encoding="latin1")
  File "/home/wilson/anaconda3/envs/d2conv3d/lib/python3.8/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/wilson/anaconda3/envs/d2conv3d/lib/python3.8/site-packages/torch/serialization.py", line 922, in _legacy_load
    raise RuntimeError("Invalid magic number; corrupt file?")
RuntimeError: Invalid magic number; corrupt file?

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

It seems can be only read by

```
with open(weights_path, "rb") as f:
    caffe2_checkpoint = pickle.load(f, encoding="latin1")
```
How can I use this '.pkl' file?

**Comment by Schmiddo** [comment]
Hey, thank you for pointing out this issue!
The weights have to be converted to pytorch's format. I uploaded a script that you can use for this, e.g. after downloading the irCSN152-sports1m-pretrained model:
```shell
python convert_csn_weights.py irCSN_152_ft_kinetics_from_sports1m_f101599884.pkl resnet152_csn_ir
```
The arguments to the script are
1. The path to the backbone weights
2. The architecture of the backbone (the script supports `resnet50_csn_ir`, `resnet152_csn_ir`, and `resnet152_csn_ip`).

The script will issue warnings about the batchnorm epsilon, which is set to 1e-3 for these models. Pytorch uses 1e-5 by default, and does not save this parameter to the state dict, so it needs to be set each time the model is used. The example configurations in this code base do this (by setting the `model.backbone.norm_layer_eps` parameter), and it is critical to set if you're using frozen batchnorm.

Hope this helps!

**Comment by WilsonAir** [comment]
邮件已收到，感谢您的来信，我将尽快给您回复。魏后胜I have received your email. Thank you for your letter. I will reply to you as soon as possible.Housheng Wei
